[pytest]

markers =
    smoke:
    regression:
    api:
    web:

    # маркеры функ. пока не нужны

    # маркеры для позитивных/негативных пока не нужны

    # польз. маркеры

    skip_flaky: Флакающие тесты с необходимостью ресерча
    bug(TFS/JIRA): Тесты, ожидаемо падающие из-за бага



